#' fn.PCA.Gauss
#'
#' Check whether first two principal components are Gaussian
#'
#' @param doc  documentation for the analysis, default if the function name
#' @param data  R matrix or data frame containing the data to be analyzed
#' @param GroupVar  name for variable defining grouping, " " if no grouping
#' @param Groups  vector of values of group variable for which
#' plots are to be done; if "All"', use all groups
#' @param AnalyticVars  vector of names (character values) of analytic results
#' @param QQtest  Logical, should plots of simulated data generated by the function qqtest be shown, default is T
#' @param folder  folder in which the excel file is to be stored, default is " " (no file is created)
#' @param ds.pvalues  excel file with Anderson-Darling and Mardia p-values, with
#' extension .csv
#'
#' @return The function produces Q-Q plots of the first two principal components for each group, and, if QQtest=T,
#'    confidence envelopes for the corresponding Q-Q plots based on simulated data.  The function returns a list with the
#'    following components:
#' \itemize{
#'   \item{"usage"}{ a vector with the contents of the argument doc, the date run, the version of R used}
#'   \item{"dataUsed"}{ the contents of the argument data restricted to the groups used}
#'   \item{"params.grouping"}{ a list with the values of the arguments GroupVar and Groups}
#'   \item{"analyticVars"}{ a vector with the value of the argument AnalyticVars}
#'   \item{"params.logical"}{ the value of QQtest}
#'   \item{"p.values"}{ a data frame with the p-values for the Gaussian assumptions for each group specified}
#'   \item{"files"}{ if folder != " ", a character string with the path to the file containing the p-values}
#'  }
#'
#' @import MASS nortest qqtest MVN
#'
#' @examples
#' data(ObsidianSources)
#' analyticVars<-c("Rb","Sr","Y","Zr","Nb")
#' pca.Gauss <- fn.pca.Gauss(data=ObsidianSources, GroupVar="Code",Groups="All", AnalyticVars=analyticVars)
#'
#' @export
#'

fn.pca.Gauss <-
  function(doc = "fn.pca.Gauss",
           data,
           GroupVar,
           Groups,
           AnalyticVars,
           QQtest = T,
           folder = " ",
           ds.pvalues ) {

    # restrict to desired set of groups
    if (Groups[1] != "All") {
      Use.rows <- (data[, GroupVar] %in% Groups)
      data.Used <- data[Use.rows, c(GroupVar, AnalyticVars)]
    } else
      data.Used <- data[, c(GroupVar, AnalyticVars)]
    # define variable groups as groups used in analysis
    if (Groups[1] == "All")
      groups <-
        as.character(unique(data.Used[, GroupVar]))
    else
      groups <- as.character(Groups)
    pca <- prcomp(data.Used[, AnalyticVars], scale = TRUE)
    # predicted values for first two components
    predict.pc1 <- predict(pca)[, 1]
    predict.pc2 <- predict(pca)[, 2]
    # add numeric code for group to data set
    GroupIndex <- rep(NA, nrow(data.Used))
    for (i in 1:nrow(data.Used)) {
      for (j in 1:length(groups))
        if (data.Used[i, GroupVar] == groups[j])
          GroupIndex[i] <- j
    }

    pvalues <-
      matrix(NA, length(groups), 6)  # Anderson-Darling, Shapiro-Wilk, Mardia test p-values
    dimnames(pvalues) <-
      list(
        groups,
        c(
          "ADpc.1",
          "ADpc.2",
          "SWpc.1",
          "SWpc.2",
          "Mardia.skew",
          "Mardia.kurtosis"
        )
      )

    Predicted <-
      data.frame(group = as.character(data.Used[, GroupVar]),
                 GroupIndex = GroupIndex,
                 predict(pca))

    n.pages <-
      round((length(groups) + 1) / 2, dig = 0)  # number of pages of plots, 2 groups to a page
    i.group <- 0  # initialize choice for group
    # qq plots and Anderson-Darling p-values
    fn.plot <- function() {
      temp <-
        Predicted[Predicted[, "group"] == groups[i.group], c("PC1", "PC2")]
      temp1 <- temp[, "PC1"]
      qqnorm(temp1, main = paste("pc.1: source", groups[i.group]))
      qqline(temp1)
      temp2 <- temp[, "PC2"]
      qqnorm(temp2, main = paste("pc.2: source", groups[i.group]))
      qqline(temp2)
      ADp1 <- round(ad.test(temp1)$p.value, dig = 3)
      ADp2 <- round(ad.test(temp2)$p.value, dig = 3)
      SWp1 <-
        round(uniNorm(temp1, type = "SW")[[2]]$p.value, dig = 3)
      SWp2 <-
        round(uniNorm(temp2, type = "SW")[[2]]$p.value, dig = 3)
      browser()
      mardia <- mardiaTest(data = temp)
      if (nrow(temp) >= 20)
        p.kurtosis <-
        round(mardia@p.value.kurt, dig = 3)
      else
        p.kurtosis <- round(mardia@p.value.small, dig = 3)
      c(ADp1,
        ADp2,
        SWp1,
        SWp2,
        round(mardia@p.value.skew, dig = 3),
        p.kurtosis)
    }
    for (page in 1:n.pages) {
      plot.new()
      par(mfrow = c(2, 2))
      i.group <- i.group + 1  #  first group for this row and page
      pvalues[i.group,] <- fn.plot()
      i.group <- i.group + 1  # second group
      if (i.group <= length(groups))
        pvalues[i.group,] <- fn.plot()
      browser()
    }
    # diagnostic plots from Mardia test multivariate diagnostic plots
    fn.Mardia.plot <- function() {
      temp <-
        Predicted[Predicted[, "group"] == groups[i.group], c("PC1", "PC2")]
      mardia <- mardiaTest(data = temp)
      mvnPlot(mardia, type = "persp")
      mvnPlot(mardia, type = "contour")
    }
    i.group <- 0
    for (page in 1:n.pages) {
      plot.new()
      par(mfrow = c(2, 2))
      i.group <- i.group + 1  #  first group for this row and page
      fn.Mardia.plot()
      i.group <- i.group + 1  # second group
      if (i.group <= length(groups))
        fn.Mardia.plot()
      browser()
    }
    if (QQtest) {
      # plots using qqtest() qq plots and Anderson-Darling p-values
      fn.qqtest <- function() {
        temp <-
          Predicted[Predicted[, "group"] == groups[i.group], c("PC1", "PC2")]
        temp1 <- temp[, "PC1"]
        qqtest(
          data = temp1,
          dist = "normal",
          drawPercentiles = T,
          main = paste("pc.1: source",
                       groups[i.group])
        )
        temp2 <- temp[, "PC2"]
        qqtest(
          data = temp2,
          dist = "normal",
          drawPercentiles = T,
          main = paste("pc.2: source",
                       groups[i.group])
        )
      }
      i.group <- 0  # initialize choice for group
      for (page in 1:n.pages) {
        plot.new()
        par(mfrow = c(2, 2))
        i.group <-
          i.group + 1  #  first group for this row and page
        fn.qqtest()
        i.group <- i.group + 1  # second group
        if (i.group <= length(groups))
          fn.qqtest()
        browser()
      }
    }
    if (substr(folder,1,1) != " ")  write.csv(pvalues, paste(folder, ds.pvalues, sep = ""))
    #
    fcn.date.ver<-paste(doc,date(),R.Version()$version.string)
    params.grouping<-list(GroupVar,Groups)
    names(params.grouping)<-c("GroupVar","Groups")
    params.logical<-QQtest
    names(params.logical)<-"QQtest"
    #
    if (substr(folder,1,1) == " ")
      out<-list(usage=fcn.date.ver,
                dataUsed=data.Used,
                analyticVars=AnalyticVars,
                params.grouping=params.grouping,
                params.logical=params.logical,
                p.values = pvalues
                )
    if (substr(folder,1,1) != " ")
      out<-list(usage=fcn.date.ver,
                dataUsed=data.Used,
                analyticVars=AnalyticVars,
                params.grouping=params.grouping,
                params.logical=params.logical,
                p.values = pvalues,
                files=paste(folder,ds.pvalues,sep="")
                )
    out
  }
